import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';
import { defineCustomElements } from '@ionic/core/loader';
import { addIcons } from 'ionicons';
import {
  add,
  alertCircle,
  arrowBack,
  arrowDown,
  arrowDownLeftBox,
  arrowForward,
  arrowUp,
  arrowUpRightBox,
  attach,
  briefcase,
  business,
  call,
  calendar,
  camera,
  checkbox,
  checkmark,
  checkmarkCircle,
  checkmarkDone,
  chevronBack,
  chevronDown,
  chevronForward,
  clipboard,
  close,
  closeCircle,
  cloudUpload,
  colorPalette,
  create,
  documentText,
  download,
  eye,
  eyeOff,
  fileTray,
  folder,
  folderOpen,
  gitNetwork,
  grid,
  gridOutline,
  list,
  listOutline,
  informationCircle,
  key,
  location,
  lockClosed,
  logIn,
  logOut,
  mail,
  menu,
  moon,
  notifications,
  paperPlane,
  people,
  barChart,
  person,
  personAdd,
  personCircle,
  pricetag,
  print,
  qrCode,
  receipt,
  receiptOutline,
  refresh,
  save,
  scan,
  statsChart,
  search,
  settings,
  shieldCheckmark,
  shieldOutline,
  squareOutline,
  time,
  trash,
  businessOutline,
  folderOutline,
  createOutline,
  trashOutline,
  closeOutline,
  lockClosedOutline,
  personAddOutline,
  pricetagOutline,
  layersOutline,
  optionsOutline,
  bookmarkOutline,
  peopleOutline,
  searchOutline,
  shieldCheckmarkOutline,
  chevronUpOutline,
  chevronDownOutline,
  arrowUpOutline,
  arrowDownOutline,
  checkmarkOutline,
  sparklesOutline,
  colorPaletteOutline,
  swapVerticalOutline,
  addCircleOutline,
  addOutline,
  informationCircleOutline,
  cut,
  cutOutline,
  link,
  linkOutline,
  unlink,
  unlinkOutline,
  copy,
  copyOutline,
  warning,
  warningOutline,
  briefcaseOutline,
  navigate,
  navigateOutline,
  qrCodeOutline,
  openOutline,
  printOutline,
  timeOutline,
  flame,
  flameOutline,
  flagOutline,
  notificationsOutline,
  documentOutline,
  checkmarkCircleOutline,
} from 'ionicons/icons';

addIcons({
  add,
  alertCircle,
  arrowBack,
  arrowDown,
  'arrow-down-left': arrowDownLeftBox,
  arrowForward,
  arrowUp,
  'arrow-up-right': arrowUpRightBox,
  attach,
  briefcase,
  'building': business,
  business,
  'business-outline': businessOutline,
  call,
  calendar,
  camera,
  checkbox,
  checkmark,
  'checkmark-outline': checkmarkOutline,
  checkmarkCircle,
  checkmarkDone,
  chevronBack,
  'chevron-back': chevronBack,
  chevronDown,
  'chevron-down': chevronDown,
  'chevron-down-outline': chevronDownOutline,
  chevronForward,
  'chevron-forward': chevronForward,
  'chevron-up-outline': chevronUpOutline,
  clipboard,
  close,
  'close-outline': closeOutline,
  closeCircle,
  cloudUpload,
  colorPalette,
  'color-palette-outline': colorPaletteOutline,
  create,
  'create-outline': createOutline,
  documentText,
  'document-text': documentText,
  download,
  eye,
  eyeOff,
  fileTray,
  folder,
  'folder-outline': folderOutline,
  folderOpen,
  gitNetwork,
  grid,
  'grid-outline': gridOutline,
  'list': list,
  'list-outline': listOutline,
  informationCircle,
  key,
  'layers-outline': layersOutline,
  location,
  lockClosed,
  'lock-closed-outline': lockClosedOutline,
  logIn,
  logOut,
  mail,
  menu,
  moon,
  notifications,
  'options-outline': optionsOutline,
  paperPlane,
  people,
  'people-outline': peopleOutline,
  person,
  personAdd,
  'person-add-outline': personAddOutline,
  personCircle,
  pricetag,
  'pricetag-outline': pricetagOutline,
  'bookmark-outline': bookmarkOutline,
  print,
  qrCode,
  receipt,
  'receipt-outline': receiptOutline,
  refresh,
  save,
  scan,
  statsChart,
  'stats-chart': statsChart,
  barChart,
  'bar-chart': barChart,
  search,
  'search-outline': searchOutline,
  settings,
  shieldCheckmark,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  shieldOutline,
  'sparkles-outline': sparklesOutline,
  squareOutline,
  'swap-vertical-outline': swapVerticalOutline,
  time,
  trash,
  'trash-outline': trashOutline,
  'arrow-up-outline': arrowUpOutline,
  'arrow-down-outline': arrowDownOutline,
  'add-circle-outline': addCircleOutline,
  'add-outline': addOutline,
  'information-circle-outline': informationCircleOutline,
  cut,
  'cut-outline': cutOutline,
  link,
  'link-outline': linkOutline,
  unlink,
  'unlink-outline': unlinkOutline,
  copy,
  'copy-outline': copyOutline,
  warning,
  'warning-outline': warningOutline,
  'briefcase-outline': briefcaseOutline,
  navigate,
  'navigate-outline': navigateOutline,
  'qr-code-outline': qrCodeOutline,
  'open-outline': openOutline,
  'print-outline': printOutline,
  'time-outline': timeOutline,
  flame,
  'flame-outline': flameOutline,
  'flag-outline': flagOutline,
  'notifications-outline': notificationsOutline,
  'document-outline': documentOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
});

defineCustomElements();

bootstrapApplication(AppComponent, appConfig).catch((error) =>
  console.error(error),
);
